spring:
 profiles:
  active:
  - dev
---
spring:
 profiles: dev   #開發環境
 application:
  name: microservicecloud-config-sky-dev
---
spring: 
 profiles: test  #測試環境
 application:
  name: microservicecloud-config-sky-sit

#必存為utf-8